# Imagen base
FROM node:14-alpine

# Define la ruta de trabajo dentro del contenedor
WORKDIR /app

# Copia los archivos del proyecto al contenedor
COPY package*.json ./

# Instala las dependencias del proyecto
RUN npm install

# Copia el resto de los archivos del proyecto al contenedor
COPY . .

# Expone el puerto 3000 del contenedor
EXPOSE 3000

# Inicia la aplicación
CMD ["npm", "start"]
