trigger:
- main

pool:
  name: 'AgentPP01'  # Usando tu self-hosted agent pool

steps:
# Descargar el archivo index.php desde GitHub en el self-hosted agent
- script: |
    wget -O $(Pipeline.Workspace)/index.php https://raw.githubusercontent.com/leandroamore/ppdemo/main/index.php
  displayName: 'Descargar index.php desde GitHub'

# Copiar el archivo a VM1 usando SSH
- task: SSH@0
  inputs:
    sshEndpoint: 'vm1-ssh'
    runOptions: 'commands'
    commands: |
      sudo rm -rf /var/www/html/index.php
      scp $(Pipeline.Workspace)/index.php adminuser@10.0.1.4:/var/www/html/index.php
      sudo systemctl restart nginx

# Copiar el archivo a VM2 usando SSH
- task: SSH@0
  inputs:
    sshEndpoint: 'vm2-ssh'
    runOptions: 'commands'
    commands: |
      sudo rm -rf /var/www/html/index.php
      scp $(Pipeline.Workspace)/index.php adminuser@10.0.1.5:/var/www/html/index.php
      sudo systemctl restart nginx
