trigger:
- main

pool:
  name: 'AgentPP01'  # Cambiado para usar tu agent pool self-hosted

steps:
- task: SSH@0
  inputs:
    sshEndpoint: 'vm1-ssh'
    runOptions: 'commands'
    commands: |
      sudo rm -rf /var/www/html/index.php
      sudo wget -O /var/www/html/index.php https://raw.githubusercontent.com/leandroamore/ppdemo/main/index.php
      sudo systemctl restart nginx

- task: SSH@0
  inputs:
    sshEndpoint: 'vm2-ssh'
    runOptions: 'commands'
    commands: |
      sudo rm -rf /var/www/html/index.php
      sudo wget -O /var/www/html/index.php https://raw.githubusercontent.com/leandroamore/ppdemo/main/index.php
      sudo systemctl restart nginx
