trigger:
- main

pool:
  name: 'AgentPP01'  # Usando tu self-hosted agent pool en Windows

steps:
# Descargar el archivo index.php desde GitHub en el self-hosted agent con PowerShell
- powershell: |
    Invoke-WebRequest -Uri "https://raw.githubusercontent.com/leandroamore/ppdemo/main/index.php" -OutFile "$(Pipeline.Workspace)\index.php"
  displayName: 'Descargar index.php desde GitHub'

# Copiar el archivo a VM1 usando la tarea Copy Files Over SSH
- task: CopyFilesOverSSH@0
  inputs:
    sshEndpoint: 'vm1-ssh'   # Asegúrate de que la conexión SSH esté configurada correctamente
    sourceFolder: '$(Pipeline.Workspace)'  # Carpeta donde se descargó el archivo en el agente
    contents: 'index.php'  # Archivo a copiar
    targetFolder: '/var/www/html'  # Carpeta en la VM donde se copiará el archivo
    cleanTargetFolder: false  # No eliminar archivos anteriores
    overwrite: true  # Sobrescribir el archivo si ya existe

# Copiar el archivo a VM2 usando la tarea Copy Files Over SSH
- task: CopyFilesOverSSH@0
  inputs:
    sshEndpoint: 'vm2-ssh'  # Mismo proceso para la segunda VM
    sourceFolder: '$(Pipeline.Workspace)'
    contents: 'index.php'
    targetFolder: '/var/www/html'
    cleanTargetFolder: false
    overwrite: true
