trigger:
- main

pool:
  name: 'AgentPP01'  # Usando el self-hosted agent pool

steps:
# Descargar el archivo demodb.bacpac desde GitHub
- powershell: |
    Invoke-WebRequest -Uri "https://github.com/leandroamore/ppdemo/blob/main/demodb.bacpac" -OutFile "$(Pipeline.Workspace)\demodb.bacpac"
  displayName: 'Descargar demodb.bacpac desde GitHub'

# Restaurar la base de datos en Azure SQL Server usando SqlPackage
- powershell: |
    $bacpacPath = "$(Pipeline.Workspace)\demodb.bacpac"
    $connectionString = "Data Source=sql-server-eber-eval.database.windows.net;Initial Catalog=demo-sql-db;User ID=sqladmin;Password=Password123!;"

    # Ejecutar la restauración usando SqlPackage
    SqlPackage /Action:Import /SourceFile:$bacpacPath /TargetConnectionString:$connectionString
  displayName: 'Restaurar base de datos desde demodb.bacpac a Azure SQL'
