trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: SSH@0
  inputs:
    sshEndpoint: 'vm1-ssh'  # Nombre de la conexión SSH en Azure DevOps
    runOptions: 'commands'
    commands: |
      sudo rm -rf /var/www/html/index.php
      sudo wget -O /var/www/html/index.php https://raw.githubusercontent.com/leandroamore/ppdemo/main/index.php
      sudo systemctl restart nginx

- task: SSH@0
  inputs:
    sshEndpoint: 'vm2-ssh'  # Nombre de la conexión SSH en Azure DevOps
    runOptions: 'commands'
    commands: |
      sudo rm -rf /var/www/html/index.php
      sudo wget -O /var/www/html/index.php https://raw.githubusercontent.com/leandroamore/ppdemo/main/index.php
      sudo systemctl restart nginx
